{"uid":"84daaefc0adb3850","name":"Тест Авторизации для теста Параметров по Подуслуге","fullName":"tests.test_target#test_target_authorization_correct","historyId":"1ba7639c67e88f2d244bf20f0a850709","time":{"start":1732160575666,"stop":1732160575666,"duration":0},"description":"Этот тест проверяет успешность авторизации в качестве заданного пользователя","descriptionHtml":"<p>Этот тест проверяет успешность авторизации в качестве заданного пользователя</p>\n","status":"broken","statusMessage":"aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gosuslugi29.ru:443 ssl:False [Connect call failed ('77.83.151.43', 443)]","statusTrace":"self = <aiohttp.connector.TCPConnector object at 0x7fc53bd71c50>\nreq = <aiohttp.client_reqrep.ClientRequest object at 0x7fc53bd72f10>\ntimeout = ClientTimeout(total=300, connect=None, sock_read=None, sock_connect=None)\nclient_error = <class 'aiohttp.client_exceptions.ClientConnectorError'>\nargs = (functools.partial(<class 'aiohttp.client_proto.ResponseHandler'>, loop=<_UnixSelectorEventLoop running=False closed=False debug=False>), '77.83.151.43', 443)\nkwargs = {'family': <AddressFamily.AF_INET: 2>, 'flags': <AddressInfo.AI_NUMERICHOST|AI_NUMERICSERV: 1028>, 'local_addr': None, 'proto': 6, ...}\n\n    async def _wrap_create_connection(\n        self,\n        *args: Any,\n        req: \"ClientRequest\",\n        timeout: \"ClientTimeout\",\n        client_error: Type[Exception] = ClientConnectorError,\n        **kwargs: Any,\n    ) -> Tuple[asyncio.Transport, ResponseHandler]:\n        try:\n            async with ceil_timeout(timeout.sock_connect):\n>               return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa\n\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py:980: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py:1086: in create_connection\n    raise exceptions[0]\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py:1070: in create_connection\n    sock = await self._connect_sock(\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py:974: in _connect_sock\n    await self.sock_connect(sock, address)\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/selector_events.py:638: in sock_connect\n    return await fut\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <_UnixSelectorEventLoop running=False closed=False debug=False>\nfut = None, sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>\naddress = ('77.83.151.43', 443)\n\n    def _sock_connect_cb(self, fut, sock, address):\n        if fut.done():\n            return\n    \n        try:\n            err = sock.getsockopt(socket.SOL_SOCKET, socket.SO_ERROR)\n            if err != 0:\n                # Jump to any except clause below.\n>               raise OSError(err, f'Connect call failed {address}')\nE               ConnectionRefusedError: [Errno 111] Connect call failed ('77.83.151.43', 443)\n\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/selector_events.py:678: ConnectionRefusedError\n\nThe above exception was the direct cause of the following exception:\n\nrequest = <SubRequest 'target_pages' for <Function test_target_service_pages[IP]>>\n\n    @pytest.fixture(scope=\"session\")\n    async def target_pages(request):\n        Authorization.authdata[\"citizenCategory\"]=request.param\n>       pages = await call_pages(request.config.servicetargets if request.param==Authorization.FLCategory else request.config.servicetargetsretry)\n\ntests/test_target.py:94: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/test_target.py:77: in call_pages\n    pages[\"ajax\"] = await utils.get_service_pages(session, utils.AuthorizationServiceMethods)\nutils/utils.py:161: in get_service_pages\n    ajaxresponse = await session.request(**ConfigUrl, url=buildurl(**UrlPart))\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/client.py:536: in _request\n    conn = await self._connector.connect(\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py:540: in connect\n    proto = await self._create_connection(req, traces, timeout)\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py:901: in _create_connection\n    _, proto = await self._create_direct_connection(req, traces, timeout)\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py:1209: in _create_direct_connection\n    raise last_exc\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py:1178: in _create_direct_connection\n    transp, proto = await self._wrap_create_connection(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <aiohttp.connector.TCPConnector object at 0x7fc53bd71c50>\nreq = <aiohttp.client_reqrep.ClientRequest object at 0x7fc53bd72f10>\ntimeout = ClientTimeout(total=300, connect=None, sock_read=None, sock_connect=None)\nclient_error = <class 'aiohttp.client_exceptions.ClientConnectorError'>\nargs = (functools.partial(<class 'aiohttp.client_proto.ResponseHandler'>, loop=<_UnixSelectorEventLoop running=False closed=False debug=False>), '77.83.151.43', 443)\nkwargs = {'family': <AddressFamily.AF_INET: 2>, 'flags': <AddressInfo.AI_NUMERICHOST|AI_NUMERICSERV: 1028>, 'local_addr': None, 'proto': 6, ...}\n\n    async def _wrap_create_connection(\n        self,\n        *args: Any,\n        req: \"ClientRequest\",\n        timeout: \"ClientTimeout\",\n        client_error: Type[Exception] = ClientConnectorError,\n        **kwargs: Any,\n    ) -> Tuple[asyncio.Transport, ResponseHandler]:\n        try:\n            async with ceil_timeout(timeout.sock_connect):\n                return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa\n        except cert_errors as exc:\n            raise ClientConnectorCertificateError(req.connection_key, exc) from exc\n        except ssl_errors as exc:\n            raise ClientConnectorSSLError(req.connection_key, exc) from exc\n        except OSError as exc:\n            if exc.errno is None and isinstance(exc, asyncio.TimeoutError):\n                raise\n>           raise client_error(req.connection_key, exc) from exc\nE           aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gosuslugi29.ru:443 ssl:False [Connect call failed ('77.83.151.43', 443)]\n\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py:988: ClientConnectorError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop_policy","time":{"start":1732159863830,"stop":1732159863830,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"target_pages","time":{"start":1732160574827,"stop":1732160575131,"duration":304},"status":"broken","statusMessage":"aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gosuslugi29.ru:443 ssl:False [Connect call failed ('77.83.151.43', 443)]\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 897, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py\", line 366, in _async_fixture_wrapper\n    return event_loop.run_until_complete(setup())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py\", line 654, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py\", line 363, in setup\n    res = await func(**_add_kwargs(func, kwargs, event_loop, request))\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/test-gosuslugi29/test-gosuslugi29/tests/test_target.py\", line 94, in target_pages\n    pages = await call_pages(request.config.servicetargets if request.param==Authorization.FLCategory else request.config.servicetargetsretry)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/test-gosuslugi29/test-gosuslugi29/tests/test_target.py\", line 77, in call_pages\n    pages[\"ajax\"] = await utils.get_service_pages(session, utils.AuthorizationServiceMethods)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/test-gosuslugi29/test-gosuslugi29/utils/utils.py\", line 161, in get_service_pages\n    ajaxresponse = await session.request(**ConfigUrl, url=buildurl(**UrlPart))\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/client.py\", line 536, in _request\n    conn = await self._connector.connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py\", line 540, in connect\n    proto = await self._create_connection(req, traces, timeout)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py\", line 901, in _create_connection\n    _, proto = await self._create_direct_connection(req, traces, timeout)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py\", line 1209, in _create_direct_connection\n    raise last_exc\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py\", line 1178, in _create_direct_connection\n    transp, proto = await self._wrap_create_connection(\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py\", line 988, in _wrap_create_connection\n    raise client_error(req.connection_key, exc) from exc\n","steps":[{"name":"Асинхронно сделать запрос к вспомогательной странице https://gosuslugi29.ru/util/ajaxRpc.sx?v=%7B%22id%22%3A1%2C%20method%3A%22system.listMethods%22%2C%20%22params%22%3A%5B%5D%7D","time":{"start":1732160574827,"stop":1732160575130,"duration":303},"status":"broken","statusMessage":"aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gosuslugi29.ru:443 ssl:False [Connect call failed ('77.83.151.43', 443)]\n","statusTrace":"  File \"/home/runner/work/test-gosuslugi29/test-gosuslugi29/utils/utils.py\", line 161, in get_service_pages\n    ajaxresponse = await session.request(**ConfigUrl, url=buildurl(**UrlPart))\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/client.py\", line 536, in _request\n    conn = await self._connector.connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py\", line 540, in connect\n    proto = await self._create_connection(req, traces, timeout)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py\", line 901, in _create_connection\n    _, proto = await self._create_direct_connection(req, traces, timeout)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py\", line 1209, in _create_direct_connection\n    raise last_exc\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py\", line 1178, in _create_direct_connection\n    transp, proto = await self._wrap_create_connection(\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/aiohttp/connector.py\", line 988, in _wrap_create_connection\n    raise client_error(req.connection_key, exc) from exc\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"severity","value":"blocker"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_target"},{"name":"host","value":"fv-az1487-134"},{"name":"thread","value":"2066-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_target"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"target_pages","value":"'IP'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"blocker","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":9,"passed":0,"unknown":0,"total":10},"items":[{"uid":"2c108b301cb70273","reportUrl":"https://justfriendlyneighbor.github.io/test-gosuslugi29/85//#testresult/2c108b301cb70273","status":"skipped","statusDetails":"Skipped: Completed succesfully, skipping from report","time":{"start":1731901671143,"stop":1731901671149,"duration":6}},{"uid":"3b9673415cf1cd74","reportUrl":"https://justfriendlyneighbor.github.io/test-gosuslugi29/84//#testresult/3b9673415cf1cd74","status":"skipped","statusDetails":"Skipped: Completed succesfully, skipping from report","time":{"start":1731555527391,"stop":1731555527396,"duration":5}},{"uid":"632af38146267e2e","reportUrl":"https://justfriendlyneighbor.github.io/test-gosuslugi29/83//#testresult/632af38146267e2e","status":"skipped","statusDetails":"Skipped: Completed succesfully, skipping from report","time":{"start":1731297601785,"stop":1731297601792,"duration":7}},{"uid":"1c4347a79b914b45","reportUrl":"https://justfriendlyneighbor.github.io/test-gosuslugi29/82//#testresult/1c4347a79b914b45","status":"skipped","statusDetails":"Skipped: Completed succesfully, skipping from report","time":{"start":1730951313525,"stop":1730951313531,"duration":6}},{"uid":"3ebfbc043cd9d882","reportUrl":"https://justfriendlyneighbor.github.io/test-gosuslugi29/81//#testresult/3ebfbc043cd9d882","status":"skipped","statusDetails":"Skipped: Completed succesfully, skipping from report","time":{"start":1730691793873,"stop":1730691793878,"duration":5}},{"uid":"91db26b84708c9b7","reportUrl":"https://justfriendlyneighbor.github.io/test-gosuslugi29/80//#testresult/91db26b84708c9b7","status":"skipped","statusDetails":"Skipped: Completed succesfully, skipping from report","time":{"start":1730362431737,"stop":1730362431742,"duration":5}},{"uid":"d0a683da56f93147","reportUrl":"https://justfriendlyneighbor.github.io/test-gosuslugi29/79//#testresult/d0a683da56f93147","status":"skipped","statusDetails":"Skipped: Completed succesfully, skipping from report","time":{"start":1730346065578,"stop":1730346065585,"duration":7}},{"uid":"ae509cdb1e41e45e","reportUrl":"https://justfriendlyneighbor.github.io/test-gosuslugi29/78//#testresult/ae509cdb1e41e45e","status":"skipped","statusDetails":"Skipped: Completed succesfully, skipping from report","time":{"start":1730300674802,"stop":1730300674809,"duration":7}},{"uid":"4faf7c3bbffafee9","reportUrl":"https://justfriendlyneighbor.github.io/test-gosuslugi29/77//#testresult/4faf7c3bbffafee9","status":"skipped","statusDetails":"Skipped: Completed succesfully, skipping from report","time":{"start":1730292857009,"stop":1730292857015,"duration":6}}]},"tags":[]},"source":"84daaefc0adb3850.json","parameterValues":["'IP'"]}